name: Claim CI on PR closed

on:
  pull_request:
    branches:
      - main
    types: [closed]

jobs:
  claim_bounty:
      name: Claim the bounty
      if: ${{ github.event_name == 'pull_request' && github.event.action == 'closed' && github.event.pull_request.merged == true }}
      runs-on: ubuntu-latest
      environment: Test-env
      env:
        GITHUB_USER: ${{ github.event.pull_request.user.login }}
        NGROK_SERVER: ${{ vars.NGROK_SERVER }}

      steps:
        - name: Extract issue ID
          id: extract_issue_id
          run: |
            export GITHUB_ISSUE_HREF=$(echo "${{ github.event.pull_request.body }}" | grep -o -E 'Closes #[0-9]+' | sed -n '1s/Closes #//p')
            echo "GITHUB_ISSUE_HREF=$GITHUB_ISSUE_HREF" >> $GITHUB_ENV

        - name: Log GitHub context
          env:
            GITHUB_CONTEXT: ${{ toJson(github) }}
          run: echo "$GITHUB_CONTEXT"

        - name: Checkout Code
          uses: actions/checkout@v2

        - name: Install Node.js
          uses: actions/setup-node@v2
          with:
            node-version: '21'

        - name: Install Truffle
          run: |
            cd truffle/
            npm install -g truffle

        - name: Install Dependencies
          run: |
            cd truffle/
            npm install

        - name: Claim Bounty
          run: |
            cd truffle/
            truffle exec scripts/claimBounty.js --network remote_ganache
